#
# Copyright (c) 2025 Robert von Burg <eitch@eitchnet.ch>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

mail.failedToSend=Failed to send email to host {host} with subject {subject} to {recipients} due to {reason}
mail.failedToSendWithAttachment=Failed to send email to host {host} with subject {subject} with attachment {fileName} to {recipients} due to {reason}
execution.handler.invalidState=ExecutionHandler has state {state}, can not start new jobs!
execution.handler.failed.execution=Failed to set to execution due to {reason}
execution.handler.failed.executed=Failed to set to executed due to {reason}
execution.handler.failed.stopped=Failed to set to execution due to {reason}
execution.handler.failed.error=Failed to set to execution due to {reason}
execution.handler.failed.warning=Failed to set to execution due to {reason}
execution.handler.failed.archive=Failed to archive due to {reason}
execution.handler.migrations.version=Migrated to version {version}
execution.policy.reservation.alreadyReserved=Can not reserve {resourceLoc} as it is already reserved!
